# Code generated by github.com/polytomic/terraform-provider-polytomic/importer
terraform {
  required_providers {
    polytomic = {
      source = "polytomic/polytomic"
    }
  }
}

provider "polytomic" {
  # Configuration comes from environment variables:
  # POLYTOMIC_DEPLOYMENT_URL
  # POLYTOMIC_API_KEY or POLYTOMIC_DEPLOYMENT_KEY or POLYTOMIC_PARTNER_KEY
}


data "polytomic_caller_identity" "self" {}

locals {
  organization_id = data.polytomic_caller_identity.self.organization_id
}


data "polytomic_hubspot_connection" "hubspot" {
  id = "6723ae9f-2b55-42d2-bc85-eed65a291cf8"
}

data "polytomic_postgresql_connection" "postgresql" {
  id = "5b740e0a-80f8-49dc-835c-d24e57fad02b"
}


resource "polytomic_bulk_sync" "hubspot_to_postgres" {
  name   = "Terraform test sync"
  active = false
  mode   = "replicate"
  source = {
    connection_id = data.polytomic_hubspot_connection.hubspot.id
  }
  destination = {
    connection_id = data.polytomic_postgresql_connection.postgresql.id
    configuration = jsonencode({
      schema = "hubspot_tf"
    })
  }
  schemas = [{
    enabled = true
    id      = "Contact"
  }]
  schedule = {
    frequency = "manual"
  }
}
