// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package provider

import "github.com/hashicorp/terraform-plugin-framework/provider"

var (
	connection_resources = map[string]provider.ResourceType{
		"polytomic_s3_connection":        s3ConnectionResourceType{},
		"polytomic_sqlserver_connection": sqlserverConnectionResourceType{},
		"polytomic_athena_connection":    athenaConnectionResourceType{},
	}
)
