// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/polytomic/terraform-provider-polytomic/provider/internal/client"
)

// Ensure provider defined types fully satisfy framework interfaces
var _ datasource.DataSource = &HttpenrichmentConnectionDataSource{}

// ExampleDataSource defines the data source implementation.
type HttpenrichmentConnectionDataSource struct {
	provider *client.Provider
}

func (d *HttpenrichmentConnectionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if provider := client.GetProvider(req.ProviderData, resp.Diagnostics); provider != nil {
		d.provider = provider
	}
}

func (d *HttpenrichmentConnectionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_httpenrichment_connection"
}

func (d *HttpenrichmentConnectionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: ":meta:subcategory:Connections: HTTP Enrichment Connection",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "",
				Required:            true,
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "",
				Optional:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"configuration": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"auth": schema.StringAttribute{
						MarkdownDescription: "",
						Computed:            true,
					},
					"body": schema.StringAttribute{
						MarkdownDescription: "",
						Computed:            true,
					},
					"fields": schema.StringAttribute{
						MarkdownDescription: "List of fields to be returned by the enrichment",
						Computed:            true,
					},
					"headers": schema.StringAttribute{
						MarkdownDescription: "",
						Computed:            true,
					},
					"healthcheck": schema.StringAttribute{
						MarkdownDescription: "Path to request when checking the health of this connection. No health check will be performed if left empty.",
						Computed:            true,
					},
					"input_mappings": schema.StringAttribute{
						MarkdownDescription: "List of input mappings to be used in the query. Each mapping should be a valid JSONPath expression.",
						Computed:            true,
					},
					"method": schema.StringAttribute{
						MarkdownDescription: "",
						Computed:            true,
					},
					"parameters": schema.StringAttribute{
						MarkdownDescription: "",
						Computed:            true,
					},
					"url": schema.StringAttribute{
						MarkdownDescription: "",
						Computed:            true,
					},
				},
				Optional: true,
			},
		},
	}
}

func (d *HttpenrichmentConnectionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data connectionData

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Get the connection
	client, err := d.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connection, err := client.Connections.Get(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection", err.Error())
		return
	}

	// For the purposes of this example code, hardcoding a response value to
	// save into the Terraform state.
	data.Id = types.StringPointerValue(connection.Data.Id)
	data.Name = types.StringPointerValue(connection.Data.Name)
	data.Organization = types.StringPointerValue(connection.Data.OrganizationId)
	var diags diag.Diagnostics
	data.Configuration, diags = types.ObjectValue(
		data.Configuration.AttributeTypes(ctx),
		map[string]attr.Value{
			"auth": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["auth"], "string").(string),
			),
			"body": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["body"], "string").(string),
			),
			"fields": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["fields"], "string").(string),
			),
			"headers": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["headers"], "string").(string),
			),
			"healthcheck": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["healthcheck"], "string").(string),
			),
			"input_mappings": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["inputMappings"], "string").(string),
			),
			"method": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["method"], "string").(string),
			),
			"parameters": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["parameters"], "string").(string),
			),
			"url": types.StringValue(
				getValueOrEmpty(connection.Data.Configuration["url"], "string").(string),
			),
		},
	)

	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
