// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package provider

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mitchellh/mapstructure"
	"github.com/polytomic/polytomic-go"
)

// Ensure provider defined types fully satisfy framework interfaces
var _ datasource.DataSource = &RedshiftserverlessConnectionDataSource{}

// ExampleDataSource defines the data source implementation.
type RedshiftserverlessConnectionDataSource struct {
	client *polytomic.Client
}

func (d *RedshiftserverlessConnectionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_redshiftserverless_connection"
}

func (d *RedshiftserverlessConnectionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: ":meta:subcategory:Connections: Redshift Serverless Connection",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "",
				Required:            true,
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "",
				Optional:            true,
			},
			"configuration": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"database": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            true,
						Optional:            false,
						Computed:            false,
						Sensitive:           false,
					},
					"workgroup": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            true,
						Optional:            false,
						Computed:            false,
						Sensitive:           false,
					},
					"region": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            true,
						Optional:            false,
						Computed:            false,
						Sensitive:           false,
					},
					"iam_role_arn": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            true,
						Optional:            false,
						Computed:            false,
						Sensitive:           false,
					},
					"connection_method": schema.StringAttribute{
						MarkdownDescription: "Method to use when connecting to Redshift Serverless; either `data_api` or `endpoint`",
						Required:            true,
						Optional:            false,
						Computed:            false,
						Sensitive:           false,
					},
					"serverless_endpoint": schema.StringAttribute{
						MarkdownDescription: "Required if `connection_method` is `endpoint`.",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
					},
					"override_endpoint": schema.BoolAttribute{
						MarkdownDescription: "Override the Data API endpoint for connecting to Redshift; only applicable when `connection_method`` is `data_api`.",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
					},
					"data_api_endpoint": schema.StringAttribute{
						MarkdownDescription: "Required if `override_endpoint` is `true`.",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
					},
					"use_unload": schema.BoolAttribute{
						MarkdownDescription: "Enable or disable the ability to unload data from Redshift Serverless.",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
					},
					"s3_bucket_name": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
					},
					"s3_bucket_region": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
					},
				},
				Optional: true,
			},
			"force_destroy": schema.BoolAttribute{
				MarkdownDescription: forceDestroyMessage,
				Optional:            true,
			},
		},
	}
}

func (d *RedshiftserverlessConnectionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*polytomic.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *polytomic.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *RedshiftserverlessConnectionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data connectionData

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Get the connection
	connection, err := d.client.Connections().Get(ctx, uuid.MustParse(data.Id.ValueString()))
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection", err.Error())
		return
	}

	// For the purposes of this example code, hardcoding a response value to
	// save into the Terraform state.
	data.Id = types.StringValue(connection.ID)
	data.Name = types.StringValue(connection.Name)
	data.Organization = types.StringValue(connection.OrganizationId)
	var conf RedshiftServerlessConnectionConfiguration
	err = mapstructure.Decode(connection.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError("Error decoding connection", err.Error())
		return
	}

	var diags diag.Diagnostics
	data.Configuration, diags = types.ObjectValue(
		data.Configuration.AttributeTypes(ctx),
		map[string]attr.Value{
			"database": types.StringValue(
				conf.Database,
			),
			"workgroup": types.StringValue(
				conf.Workgroup,
			),
			"region": types.StringValue(
				conf.Region,
			),
			"iam_role_arn": types.StringValue(
				conf.IAMRoleARN,
			),
			"connection_method": types.StringValue(
				conf.ConnectionMethod,
			),
			"serverless_endpoint": types.StringValue(
				conf.ServerlessEndpoint,
			),
			"override_endpoint": types.BoolValue(
				conf.OverrideEndpoint,
			),
			"data_api_endpoint": types.StringValue(
				conf.DataAPIEndpoint,
			),
			"use_unload": types.BoolValue(
				conf.UseUnload,
			),
			"s3_bucket_name": types.StringValue(
				conf.S3BucketName,
			),
			"s3_bucket_region": types.StringValue(
				conf.S3BucketRegion,
			),
		},
	)

	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
