// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/AlekSi/pointer"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/mitchellh/mapstructure"
	"github.com/polytomic/polytomic-go"
	ptcore "github.com/polytomic/polytomic-go/core"
	"github.com/polytomic/terraform-provider-polytomic/provider/internal/client"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
)

// Ensure provider defined types fully satisfy framework interfaces
var _ resource.Resource = &CsvConnectionResource{}
var _ resource.ResourceWithImportState = &CsvConnectionResource{}

func (t *CsvConnectionResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: ":meta:subcategory:Connections: CSV URL Connection",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "Organization ID",
				Optional:            true,
				Computed:            true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"configuration": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"auth": schema.SingleNestedAttribute{
						MarkdownDescription: "",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
						Attributes: map[string]schema.Attribute{
							"basic": schema.SingleNestedAttribute{
								MarkdownDescription: "",
								Required:            false,
								Optional:            true,
								Computed:            true,
								Sensitive:           false,
								Attributes: map[string]schema.Attribute{
									"password": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
									"username": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
								},
							},
							"header": schema.SingleNestedAttribute{
								MarkdownDescription: "",
								Required:            false,
								Optional:            true,
								Computed:            true,
								Sensitive:           false,
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
									"value": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
									},
								},
							},
							"oauth": schema.SingleNestedAttribute{
								MarkdownDescription: "",
								Required:            false,
								Optional:            true,
								Computed:            true,
								Sensitive:           false,
								Attributes: map[string]schema.Attribute{
									"auth_style": schema.Int64Attribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             int64default.StaticInt64(0),
									},
									"client_id": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
									"client_secret": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
									"extra_form_data": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
									"scopes": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
									"token_endpoint": schema.StringAttribute{
										MarkdownDescription: "",
										Required:            false,
										Optional:            true,
										Computed:            true,
										Sensitive:           false,
										Default:             stringdefault.StaticString(""),
									},
								},
							},
						},
					},
					"headers": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
						Default:             stringdefault.StaticString(""),
					},
					"parameters": schema.StringAttribute{
						MarkdownDescription: "",
						Required:            false,
						Optional:            true,
						Computed:            true,
						Sensitive:           false,
						Default:             stringdefault.StaticString(""),
					},
					"url": schema.StringAttribute{
						MarkdownDescription: "e.g. http://www.example.com",
						Required:            true,
						Optional:            false,
						Computed:            false,
						Sensitive:           false,
					},
				},

				Required: true,

				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
			},
			"force_destroy": schema.BoolAttribute{
				MarkdownDescription: forceDestroyMessage,
				Optional:            true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "CSV URL Connection identifier",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

type CsvConf struct {
	Auth map[string]interface{} `mapstructure:"auth" tfsdk:"auth"`

	Headers string `mapstructure:"headers" tfsdk:"headers"`

	Parameters string `mapstructure:"parameters" tfsdk:"parameters"`

	Url string `mapstructure:"url" tfsdk:"url"`
}

type CsvConnectionResource struct {
	provider *client.Provider
}

func (r *CsvConnectionResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if provider := client.GetProvider(req.ProviderData, resp.Diagnostics); provider != nil {
		r.provider = provider
	}
}

func (r *CsvConnectionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_csv_connection"
}

func (r *CsvConnectionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data connectionData

	diags := req.Config.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	created, err := client.Connections.Create(ctx, &polytomic.CreateConnectionRequestSchema{
		Name:           data.Name.ValueString(),
		Type:           "csv",
		OrganizationId: data.Organization.ValueStringPointer(),
		Configuration: map[string]interface{}{
			"auth": map[string]interface{}{
				"basic": map[string]interface{}{
					"password": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["basic"].(types.Object).Attributes()["password"].(types.String).ValueString(),
					"username": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["basic"].(types.Object).Attributes()["username"].(types.String).ValueString(),
				},
				"header": map[string]interface{}{
					"name":  data.Configuration.Attributes()["auth"].(types.Object).Attributes()["header"].(types.Object).Attributes()["name"].(types.String).ValueString(),
					"value": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["header"].(types.Object).Attributes()["value"].(types.String).ValueString(),
				},
				"oauth": map[string]interface{}{
					"auth_style":      int(data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["auth_style"].(types.Int64).ValueInt64()),
					"client_id":       data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["client_id"].(types.String).ValueString(),
					"client_secret":   data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["client_secret"].(types.String).ValueString(),
					"extra_form_data": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["extra_form_data"].(types.String).ValueString(),
					"scopes":          data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["scopes"].(types.String).ValueString(),
					"token_endpoint":  data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["token_endpoint"].(types.String).ValueString(),
				},
			},
			"headers":    data.Configuration.Attributes()["headers"].(types.String).ValueString(),
			"parameters": data.Configuration.Attributes()["parameters"].(types.String).ValueString(),
			"url":        data.Configuration.Attributes()["url"].(types.String).ValueString(),
		},
		Validate: pointer.ToBool(false),
	})
	if err != nil {
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error creating connection: %s", err))
		return
	}
	data.Id = types.StringPointerValue(created.Data.Id)
	data.Name = types.StringPointerValue(created.Data.Name)
	data.Organization = types.StringPointerValue(created.Data.OrganizationId)

	conf := CsvConf{}
	err = mapstructure.Decode(created.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error decoding connection configuration: %s", err))
	}

	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"auth": types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"basic": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"password": types.StringType,
						"username": types.StringType,
					},
				}, "header": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"name":  types.StringType,
						"value": types.StringType,
					},
				}, "oauth": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"auth_style":      types.NumberType,
						"client_id":       types.StringType,
						"client_secret":   types.StringType,
						"extra_form_data": types.StringType,
						"scopes":          types.StringType,
						"token_endpoint":  types.StringType,
					},
				},
			},
		}, "headers": types.StringType,
		"parameters": types.StringType,
		"url":        types.StringType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	tflog.Trace(ctx, "created a connection", map[string]interface{}{"type": "Csv", "id": created.Data.Id})

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *CsvConnectionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data connectionData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connection, err := client.Connections.Get(ctx, data.Id.ValueString())
	if err != nil {
		pErr := &ptcore.APIError{}
		if errors.As(err, &pErr) {
			if pErr.StatusCode == http.StatusNotFound {
				resp.State.RemoveResource(ctx)
				return
			}
		}
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error reading connection: %s", err))
		return
	}
	data.Id = types.StringPointerValue(connection.Data.Id)
	data.Name = types.StringPointerValue(connection.Data.Name)
	data.Organization = types.StringPointerValue(connection.Data.OrganizationId)

	conf := CsvConf{}
	err = mapstructure.Decode(connection.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error decoding connection configuration: %s", err))
	}

	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"auth": types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"basic": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"password": types.StringType,
						"username": types.StringType,
					},
				}, "header": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"name":  types.StringType,
						"value": types.StringType,
					},
				}, "oauth": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"auth_style":      types.NumberType,
						"client_id":       types.StringType,
						"client_secret":   types.StringType,
						"extra_form_data": types.StringType,
						"scopes":          types.StringType,
						"token_endpoint":  types.StringType,
					},
				},
			},
		}, "headers": types.StringType,
		"parameters": types.StringType,
		"url":        types.StringType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *CsvConnectionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data connectionData

	diags := req.Plan.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	updated, err := client.Connections.Update(ctx,
		data.Id.ValueString(),
		&polytomic.UpdateConnectionRequestSchema{
			Name:           data.Name.ValueString(),
			OrganizationId: data.Organization.ValueStringPointer(),
			Configuration: map[string]interface{}{
				"auth": map[string]interface{}{
					"basic": map[string]interface{}{
						"password": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["basic"].(types.Object).Attributes()["password"].(types.String).ValueString(),
						"username": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["basic"].(types.Object).Attributes()["username"].(types.String).ValueString(),
					},
					"header": map[string]interface{}{
						"name":  data.Configuration.Attributes()["auth"].(types.Object).Attributes()["header"].(types.Object).Attributes()["name"].(types.String).ValueString(),
						"value": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["header"].(types.Object).Attributes()["value"].(types.String).ValueString(),
					},
					"oauth": map[string]interface{}{
						"auth_style":      int(data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["auth_style"].(types.Int64).ValueInt64()),
						"client_id":       data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["client_id"].(types.String).ValueString(),
						"client_secret":   data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["client_secret"].(types.String).ValueString(),
						"extra_form_data": data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["extra_form_data"].(types.String).ValueString(),
						"scopes":          data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["scopes"].(types.String).ValueString(),
						"token_endpoint":  data.Configuration.Attributes()["auth"].(types.Object).Attributes()["oauth"].(types.Object).Attributes()["token_endpoint"].(types.String).ValueString(),
					},
				},
				"headers":    data.Configuration.Attributes()["headers"].(types.String).ValueString(),
				"parameters": data.Configuration.Attributes()["parameters"].(types.String).ValueString(),
				"url":        data.Configuration.Attributes()["url"].(types.String).ValueString(),
			},
			Validate: pointer.ToBool(false),
		})
	if err != nil {
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error updating connection: %s", err))
		return
	}

	data.Id = types.StringPointerValue(updated.Data.Id)
	data.Name = types.StringPointerValue(updated.Data.Name)
	data.Organization = types.StringPointerValue(updated.Data.OrganizationId)

	conf := CsvConf{}
	err = mapstructure.Decode(updated.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error decoding connection configuration: %s", err))
	}

	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"auth": types.ObjectType{
			AttrTypes: map[string]attr.Type{
				"basic": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"password": types.StringType,
						"username": types.StringType,
					},
				}, "header": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"name":  types.StringType,
						"value": types.StringType,
					},
				}, "oauth": types.ObjectType{
					AttrTypes: map[string]attr.Type{
						"auth_style":      types.NumberType,
						"client_id":       types.StringType,
						"client_secret":   types.StringType,
						"extra_form_data": types.StringType,
						"scopes":          types.StringType,
						"token_endpoint":  types.StringType,
					},
				},
			},
		}, "headers": types.StringType,
		"parameters": types.StringType,
		"url":        types.StringType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *CsvConnectionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data connectionData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	if data.ForceDestroy.ValueBool() {
		err := client.Connections.Remove(ctx, data.Id.ValueString(), &polytomic.ConnectionsRemoveRequest{
			Force: pointer.ToBool(true),
		})
		if err != nil {
			pErr := &polytomic.NotFoundError{}
			if errors.As(err, &pErr) {
				resp.State.RemoveResource(ctx)
				return
			}

			resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error deleting connection: %s", err))
		}
		return
	}

	err = client.Connections.Remove(ctx, data.Id.ValueString(), &polytomic.ConnectionsRemoveRequest{
		Force: pointer.ToBool(false),
	})
	if err != nil {
		pErr := &polytomic.NotFoundError{}
		if errors.As(err, &pErr) {
			resp.State.RemoveResource(ctx)
			return
		}
	}
	pErr := &polytomic.UnprocessableEntityError{}
	if errors.As(err, &pErr) {
		if strings.Contains(*pErr.Body.Message, "connection in use") {
			resp.Diagnostics.AddError("Connection in use",
				fmt.Sprintf("Connection is used by %s \"%s\" (%s). Please remove before deleting this connection.",
					pErr.Body.Metadata["type"], pErr.Body.Metadata["name"], pErr.Body.Metadata["id"]),
			)
			return
		}
	}

	if err != nil {
		resp.Diagnostics.AddError(clientError, fmt.Sprintf("Error deleting connection: %s", err))
	}
}

func (r *CsvConnectionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
