// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package provider

import (
	"context"
	"fmt"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
)

func TestAccSynapseConnection(t *testing.T) {
	name := "TestAcc"
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Missing configuration
			{
				Config:      testAccSynapseConnectionResourceNoConfig(name),
				ExpectError: regexp.MustCompile("The argument \"configuration\" is required, but no definition was found."),
			},
			// Empty configuration
			{
				Config:      testAccSynapseConnectionResourceMissingRequired(name),
				ExpectError: regexp.MustCompile("Inappropriate value for attribute \"configuration\":"),
			},
			{
				Config: testAccSynapseConnectionResource(name),
				Check: resource.ComposeTestCheckFunc(
					// Check if the resource exists
					testAccSynapseConnectionExists(name),
					// Check the name
					resource.TestCheckResourceAttr("polytomic_synapse_connection.test", "name", name),
				),
			},
		},
	})
}

func testAccSynapseConnectionExists(name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		_, ok := s.RootModule().Resources["polytomic_synapse_connection.test"]
		if !ok {
			return fmt.Errorf("not found: %s", "polytomic_synapse_connection.test")
		}

		client := testClient()
		connections, err := client.Connections().List(context.TODO())
		if err != nil {
			return err
		}
		var found bool
		for _, connection := range connections {
			if connection.Name == name {
				found = true
				break
			}
		}

		if !found {
			return fmt.Errorf("connection %s not found", name)
		}

		return nil

	}
}

func testAccSynapseConnectionResource(name string) string {
	return fmt.Sprintf(`
resource "polytomic_synapse_connection" "test" {
	name          = "%s"
	configuration = {
   hostname = "host.example.com"
   username = "user"
   password = "password"
   database = "database"
   port = 5439
   }
}
`, name)
}

func testAccSynapseConnectionResourceNoConfig(name string) string {
	return fmt.Sprintf(`
resource "polytomic_synapse_connection" "test" {
	name          = "%s"
}
`, name)
}

func testAccSynapseConnectionResourceMissingRequired(name string) string {
	return fmt.Sprintf(`
resource "polytomic_synapse_connection" "test" {
	name          = "%s"
	 configuration = {}
}`, name)
}
