package provider_test

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/AlekSi/pointer"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/polytomic/polytomic-go/v25"
	"github.com/polytomic/terraform-provider-polytomic/importer"
	"github.com/polytomic/terraform-provider-polytomic/internal/providerclient"
	"github.com/polytomic/terraform-provider-polytomic/provider"
	"github.com/stretchr/testify/require"
)

func TestAccSyncImporterCleanPlans(t *testing.T) { testSyncImporterCleanPlans(t, "") }

func TestAccSyncSalesforceImporterCleanPlans(t *testing.T) {
	target := os.Getenv("POLYTOMIC_SYNC_TEST_SALESFORCE_CONNECTION_ID")
	if target == "" {
		t.Skip("requires POLYTOMIC_SYNC_TEST_SALESFORCE_CONNECTION_ID")
	}
	testSyncImporterCleanPlans(t, target)
}

func testSyncImporterCleanPlans(t *testing.T, salesforce string) {
	t.Helper()
	if os.Getenv("TF_ACC") != "1" {
		t.Skip("acceptance tests require TF_ACC=1")
	}
	connectionID := os.Getenv("POLYTOMIC_SYNC_TEST_CONNECTION_ID")
	if connectionID == "" {
		connectionID, _ = provider.BulkSyncAcceptanceConnections(t)
	}
	clients, err := providerclient.NewClientProvider(providerclient.OptionsFromEnv())
	require.NoError(t, err)
	client, err := clients.Client(t.Context(), "")
	require.NoError(t, err)
	name := "TestAccSyncImporter-" + uuid.NewString()
	model, err := client.Models.Create(t.Context(), &polytomic.ModelsCreateRequest{Body: &polytomic.CreateModelRequest{
		Name: name + "-model", ConnectionID: connectionID,
		Configuration: map[string]any{"query": "SELECT email FROM polytomic.sync_test_source"},
	}})
	require.NoError(t, err)
	modelID := pointer.GetString(model.Data.ID)
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		require.NoError(t, client.Models.Delete(ctx, modelID, &polytomic.ModelsDeleteRequest{}))
	})
	request := &polytomic.CreateModelSyncV5Request{
		Name: name, Active: pointer.ToBool(false), Mode: polytomic.ModelsyncSyncTargetModeReplace,
		Target:         &polytomic.ModelSyncV5Target{ConnectionID: connectionID, Object: pointer.ToString("polytomic.sync_test_target")},
		Fields:         []*polytomic.SyncField{{Source: &polytomic.Source{ModelID: modelID, Field: "email"}, Target: "email"}},
		Schedule:       &polytomic.Schedule{Frequency: pointer.To(polytomic.ScheduleFrequencyManual)},
		SyncAllRecords: pointer.ToBool(true), OnlyEnrichUpdates: pointer.ToBool(true), SkipInitialBackfill: pointer.ToBool(true),
		Filters: []*polytomic.Filter{{Field: &polytomic.Source{ModelID: modelID, Field: "email"}, Function: polytomic.FilterFunctionEquality, Value: ""}, {Field: &polytomic.Source{ModelID: modelID, Field: "email"}, Function: polytomic.FilterFunctionIsNotNull}},
	}
	if salesforce != "" {
		request.Mode = polytomic.ModelsyncSyncTargetModeUpdate
		request.Target = &polytomic.ModelSyncV5Target{ConnectionID: salesforce, Object: pointer.ToString("Contact")}
		request.Fields[0].Target = "LastName"
		request.Identity = &polytomic.Identity{Source: &polytomic.Source{ModelID: modelID, Field: "email"}, Target: "Email", Function: polytomic.SchemaIdentityFunctionEquality}
		request.Filters = []*polytomic.Filter{{FieldType: pointer.To(polytomic.FilterFieldReferenceTypeTarget), FieldID: pointer.ToString("Email"), Function: polytomic.FilterFunctionEquality, Value: ""}, {FieldType: pointer.To(polytomic.FilterFieldReferenceTypeTarget), FieldID: pointer.ToString("Email"), Function: polytomic.FilterFunctionIsNotNull}}
	}
	created, err := client.ModelSync.Create(t.Context(), request)
	require.NoError(t, err)
	syncID := pointer.GetString(created.Data.ID)
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		response, err := client.ModelSync.Get(ctx, syncID)
		if err == nil && response.Data != nil {
			require.NoError(t, client.ModelSync.Delete(ctx, syncID))
		}
	})
	baseline, err := client.ModelSync.Get(t.Context(), syncID)
	require.NoError(t, err)
	updatedAt := pointer.Get(baseline.Data.UpdatedAt)
	exporter := importer.NewSyncs(client)
	exporter.Resources["test"] = created.Data
	var generated bytes.Buffer
	require.NoError(t, exporter.GenerateTerraformFiles(t.Context(), &generated, nil))
	directory := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(directory, "syncs.tf"), generated.Bytes(), 0600))
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: provider.GetTestAccProtoV6ProviderFactories(),
		Steps: []resource.TestStep{
			{ConfigDirectory: config.StaticDirectory(directory), ResourceName: "polytomic_sync.test", ImportState: true, ImportStateId: syncID, ImportStatePersist: true},
			{ConfigDirectory: config.StaticDirectory(directory), PlanOnly: true},
			{ConfigDirectory: config.StaticDirectory(directory), PlanOnly: true},
			{ConfigDirectory: config.StaticDirectory(directory), Check: func(*terraform.State) error {
				result, err := client.ModelSync.Get(t.Context(), syncID)
				if err != nil {
					return err
				}
				if !updatedAt.Equal(pointer.Get(result.Data.UpdatedAt)) {
					return fmt.Errorf("import/no-op workflow updated the sync audit timestamp: %s -> %s", updatedAt.Format(time.RFC3339Nano), pointer.Get(result.Data.UpdatedAt).Format(time.RFC3339Nano))
				}
				return nil
			}},
		},
	})
}
