package provider_test

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/AlekSi/pointer"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/polytomic/polytomic-go/v25"
	"github.com/polytomic/terraform-provider-polytomic/importer"
	"github.com/polytomic/terraform-provider-polytomic/internal/providerclient"
	"github.com/polytomic/terraform-provider-polytomic/provider"
	"github.com/stretchr/testify/require"
)

// Exercise the same bulk-sync exporter used by the CLI, then import its HCL
// into fresh state and check successive plans. Export only this test's sync.
func TestAccBulkSyncImporterCleanPlans(t *testing.T) {
	source, dest := provider.BulkSyncAcceptanceConnections(t)
	name := "TestAccBulkSyncImporter-" + uuid.NewString()
	directory := t.TempDir()
	clients, err := providerclient.NewClientProvider(providerclient.OptionsFromEnv())
	require.NoError(t, err)
	client, err := clients.Client(t.Context(), "")
	require.NoError(t, err)
	created, err := client.BulkSync.Create(t.Context(), &polytomic.CreateBulkSyncRequest{
		Name: name, Active: pointer.ToBool(false), Mode: pointer.To(polytomic.BulkSyncTargetModeReplicate),
		SourceConnectionID: source, DestinationConnectionID: dest,
		SourceConfiguration: map[string]any{}, DestinationConfiguration: map[string]any{"schema": "public"},
		DefaultSchedule: &polytomic.BulkSyncDefaultScheduleRequest{Frequency: polytomic.ScheduleFrequencyManual},
		Schemas:         []*polytomic.CreateBulkSyncRequestSchemasItem{{SchemaConfiguration: &polytomic.SchemaConfiguration{ID: pointer.ToString("polytomic.sync_test_source"), Enabled: pointer.ToBool(true)}}},
	})
	require.NoError(t, err)
	syncID := pointer.GetString(created.Data.ID)
	updatedAt := pointer.Get(created.Data.UpdatedAt)
	// Terraform normally destroys the imported fixture. Clean up after an
	// early export/import failure too, without touching existing syncs.
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		response, err := client.BulkSync.Get(ctx, syncID, &polytomic.BulkSyncGetRequest{})
		if err == nil && response.Data != nil {
			if err := client.BulkSync.Delete(ctx, syncID, &polytomic.BulkSyncDeleteRequest{}); err != nil {
				t.Errorf("cleaning up importer fixture: %v", err)
			}
		}
	})
	bulk := importer.NewBulkSyncs(client)
	bulk.Resources["test"] = created.Data
	var generated bytes.Buffer
	require.NoError(t, bulk.GenerateTerraformFiles(t.Context(), &generated, nil))
	require.NoError(t, os.WriteFile(filepath.Join(directory, "bulk_syncs.tf"), generated.Bytes(), 0600))
	checkAudit := func(state *terraform.State) error {
		response, err := client.BulkSync.Get(t.Context(), syncID, &polytomic.BulkSyncGetRequest{})
		if err != nil {
			return err
		}
		if !updatedAt.Equal(pointer.Get(response.Data.UpdatedAt)) {
			return fmt.Errorf("import/no-op plans updated the sync's audit timestamp")
		}
		return nil
	}
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: provider.GetTestAccProtoV6ProviderFactories(),
		Steps: []resource.TestStep{
			{ConfigDirectory: config.StaticDirectory(directory), ResourceName: "polytomic_bulk_sync.test", ImportState: true, ImportStateId: syncID, ImportStatePersist: true},
			{ConfigDirectory: config.StaticDirectory(directory), PlanOnly: true},
			{ConfigDirectory: config.StaticDirectory(directory), PlanOnly: true},
			// An ordinary apply step also enforces an empty post-apply plan and
			// checks that the no-op workflow made no API update.
			{ConfigDirectory: config.StaticDirectory(directory), Check: checkAudit},
		},
	})
}
