// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package connections

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mitchellh/mapstructure"
	"github.com/polytomic/terraform-provider-polytomic/internal/providerclient"
)

// Ensure provider defined types fully satisfy framework interfaces
var _ datasource.DataSource = &Amazon_rds_postgresqlConnectionDataSource{}

// ExampleDataSource defines the data source implementation.
type Amazon_rds_postgresqlConnectionDataSource struct {
	provider *providerclient.Provider
}

func (d *Amazon_rds_postgresqlConnectionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if provider := providerclient.GetProvider(req.ProviderData, resp.Diagnostics); provider != nil {
		d.provider = provider
	}
}

func (d *Amazon_rds_postgresqlConnectionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_amazon_rds_postgresql_connection"
}

func (d *Amazon_rds_postgresqlConnectionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: ":meta:subcategory:Connections: Amazon RDS PostgreSQL Connection",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "",
				Required:            true,
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "",
				Optional:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"configuration": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"change_detection": schema.BoolAttribute{
						MarkdownDescription: `Use logical replication for bulk syncs Default: <code>false</code>.`,
						Computed:            true,
					},
					"database": schema.StringAttribute{
						MarkdownDescription: ``,
						Computed:            true,
					},
					"external_id": schema.StringAttribute{
						MarkdownDescription: `External ID

    External ID for the IAM role`,
						Computed: true,
					},
					"hostname": schema.StringAttribute{
						MarkdownDescription: `RDS endpoint

    The Amazon RDS endpoint; custom DNS names cannot be used to generate IAM authentication tokens`,
						Computed: true,
					},
					"iam_role_arn": schema.StringAttribute{
						MarkdownDescription: `IAM role ARN

    Role that grants rds-db:connect access to this database user`,
						Computed: true,
					},
					"port": schema.Int64Attribute{
						MarkdownDescription: `Default: <code>5432</code>.`,
						Computed:            true,
					},
					"publication": schema.StringAttribute{
						MarkdownDescription: ``,
						Computed:            true,
					},
					"region": schema.StringAttribute{
						MarkdownDescription: `AWS region`,
						Computed:            true,
					},
					"ssh": schema.BoolAttribute{
						MarkdownDescription: `Connect over SSH tunnel`,
						Computed:            true,
					},
					"ssh_host": schema.StringAttribute{
						MarkdownDescription: `SSH host`,
						Computed:            true,
					},
					"ssh_port": schema.Int64Attribute{
						MarkdownDescription: `SSH port Default: <code>22</code>.`,
						Computed:            true,
					},
					"ssh_user": schema.StringAttribute{
						MarkdownDescription: `SSH user Default: <code>root</code>.`,
						Computed:            true,
					},
					"tags": schema.MapAttribute{
						MarkdownDescription: `Additional tags to apply during role assumption`,
						Computed:            true,
						ElementType:         types.StringType,
					},
					"username": schema.StringAttribute{
						MarkdownDescription: ``,
						Computed:            true,
					},
				},
				Optional: true,
			},
		},
	}
}

type Amazon_rds_postgresqlDataSourceConf struct {
	Change_detection bool              `mapstructure:"change_detection" tfsdk:"change_detection"`
	Database         string            `mapstructure:"database" tfsdk:"database"`
	External_id      string            `mapstructure:"external_id" tfsdk:"external_id"`
	Hostname         string            `mapstructure:"hostname" tfsdk:"hostname"`
	Iam_role_arn     string            `mapstructure:"iam_role_arn" tfsdk:"iam_role_arn"`
	Port             int64             `mapstructure:"port" tfsdk:"port"`
	Publication      string            `mapstructure:"publication" tfsdk:"publication"`
	Region           string            `mapstructure:"region" tfsdk:"region"`
	Ssh              bool              `mapstructure:"ssh" tfsdk:"ssh"`
	Ssh_host         string            `mapstructure:"ssh_host" tfsdk:"ssh_host"`
	Ssh_port         int64             `mapstructure:"ssh_port" tfsdk:"ssh_port"`
	Ssh_user         string            `mapstructure:"ssh_user" tfsdk:"ssh_user"`
	Tags             map[string]string `mapstructure:"tags" tfsdk:"tags"`
	Username         string            `mapstructure:"username" tfsdk:"username"`
}

func (d *Amazon_rds_postgresqlConnectionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data connectionDataSourceData

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Get the connection
	client, err := d.provider.Client(ctx, data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connection, err := client.Connections.Get(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection", err.Error())
		return
	}

	data.Id = types.StringPointerValue(connection.Data.Id)
	data.Name = types.StringPointerValue(connection.Data.Name)
	data.Organization = types.StringPointerValue(connection.Data.OrganizationId)

	conf := Amazon_rds_postgresqlDataSourceConf{}
	err = mapstructure.Decode(connection.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError("Error decoding connection configuration", err.Error())
		return
	}

	var diags diag.Diagnostics
	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"change_detection": types.BoolType,
		"database":         types.StringType,
		"external_id":      types.StringType,
		"hostname":         types.StringType,
		"iam_role_arn":     types.StringType,
		"port":             types.NumberType,
		"publication":      types.StringType,
		"region":           types.StringType,
		"ssh":              types.BoolType,
		"ssh_host":         types.StringType,
		"ssh_port":         types.NumberType,
		"ssh_user":         types.StringType,
		"tags": types.MapType{
			ElemType: types.StringType,
		}, "username": types.StringType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
