// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package connections

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mitchellh/mapstructure"
	"github.com/polytomic/terraform-provider-polytomic/internal/providerclient"
)

// Ensure provider defined types fully satisfy framework interfaces
var _ datasource.DataSource = &Google_search_ads_360ConnectionDataSource{}

// ExampleDataSource defines the data source implementation.
type Google_search_ads_360ConnectionDataSource struct {
	provider *providerclient.Provider
}

func (d *Google_search_ads_360ConnectionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if provider := providerclient.GetProvider(req.ProviderData, resp.Diagnostics); provider != nil {
		d.provider = provider
	}
}

func (d *Google_search_ads_360ConnectionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_google_search_ads_360_connection"
}

func (d *Google_search_ads_360ConnectionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: ":meta:subcategory:Connections: Google Search Ads 360 Connection",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "",
				Required:            true,
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "",
				Optional:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "",
				Computed:            true,
			},
			"configuration": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"accounts": schema.SetNestedAttribute{
						MarkdownDescription: ``,
						Computed:            true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"label": schema.StringAttribute{
									MarkdownDescription: ``,
									Computed:            true,
								},
								"value": schema.StringAttribute{
									MarkdownDescription: ``,
									Computed:            true,
								},
							},
						},
					},
					"blanket_user_consent": schema.BoolAttribute{
						MarkdownDescription: `All transmitted users consented to ad personalization and information sharing

    Causes Data Manager conversion uploads to signal that every transmitted user has accepted ad personalization and data sharing policies. This includes users in more advertising functions but requires you to have obtained express consent.`,
						Computed: true,
					},
					"connected_user": schema.StringAttribute{
						MarkdownDescription: `Connected user's email`,
						Computed:            true,
					},
					"use_data_manager_api": schema.BoolAttribute{
						MarkdownDescription: `Use Data Manager API

    Authorize this connection for the Google Data Manager API used for conversion uploads.`,
						Computed: true,
					},
				},
				Optional: true,
			},
		},
	}
}

type Google_search_ads_360DataSourceConf struct {
	Accounts []struct {
		Label string `mapstructure:"label" tfsdk:"label"`
		Value string `mapstructure:"value" tfsdk:"value"`
	} `mapstructure:"accounts" tfsdk:"accounts"`
	Blanket_user_consent bool   `mapstructure:"blanket_user_consent" tfsdk:"blanket_user_consent"`
	Connected_user       string `mapstructure:"connected_user" tfsdk:"connected_user"`
	Use_data_manager_api bool   `mapstructure:"use_data_manager_api" tfsdk:"use_data_manager_api"`
}

func (d *Google_search_ads_360ConnectionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data connectionDataSourceData

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Get the connection
	client, err := d.provider.Client(ctx, data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connection, err := client.Connections.Get(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection", err.Error())
		return
	}

	data.Id = types.StringPointerValue(connection.Data.Id)
	data.Name = types.StringPointerValue(connection.Data.Name)
	data.Organization = types.StringPointerValue(connection.Data.OrganizationId)

	conf := Google_search_ads_360DataSourceConf{}
	err = mapstructure.Decode(connection.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError("Error decoding connection configuration", err.Error())
		return
	}

	var diags diag.Diagnostics
	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"accounts": types.SetType{
			ElemType: types.ObjectType{
				AttrTypes: map[string]attr.Type{
					"label": types.StringType,
					"value": types.StringType,
				},
			},
		},
		"blanket_user_consent": types.BoolType,
		"connected_user":       types.StringType,
		"use_data_manager_api": types.BoolType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
