// Code generated by Polytomic. DO NOT EDIT.
// edit connections.yaml and re-run go generate

package connections

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/AlekSi/pointer"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/mitchellh/mapstructure"
	"github.com/polytomic/polytomic-go"
	ptcore "github.com/polytomic/polytomic-go/core"
	"github.com/polytomic/terraform-provider-polytomic/internal/providerclient"
)

// Ensure provider defined types fully satisfy framework interfaces
var _ resource.Resource = &S3ConnectionResource{}
var _ resource.ResourceWithImportState = &S3ConnectionResource{}

var S3Schema = schema.Schema{
	MarkdownDescription: ":meta:subcategory:Connections: S3 Connection",
	Attributes: map[string]schema.Attribute{
		"organization": schema.StringAttribute{
			MarkdownDescription: "Organization ID",
			Optional:            true,
			Computed:            true,
		},
		"name": schema.StringAttribute{
			Required: true,
		},
		"configuration": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"auth_mode": schema.StringAttribute{
					MarkdownDescription: `Authentication Method

    How to authenticate with AWS. Defaults to Access Key and Secret`,
					Required:  true,
					Optional:  false,
					Computed:  false,
					Sensitive: false,
				},
				"aws_access_key_id": schema.StringAttribute{
					MarkdownDescription: `AWS Access Key ID

    Access Key ID with read/write access to a bucket.`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
				"aws_secret_access_key": schema.StringAttribute{
					MarkdownDescription: `AWS Secret Access Key`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           true,
					PlanModifiers: []planmodifier.String{
						stringplanmodifier.UseStateForUnknown(),
					},
				},
				"aws_user": schema.StringAttribute{
					MarkdownDescription: `User ARN`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           false,
				},
				"csv_has_headers": schema.BoolAttribute{
					MarkdownDescription: `CSV files have headers

    Whether CSV files have a header row with field names.`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
				"directory_glob_pattern": schema.StringAttribute{
					MarkdownDescription: `Tables glob path`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           false,
				},
				"enable_event_notifications": schema.BoolAttribute{
					MarkdownDescription: `Enable Event Notifications

    Enable S3 event notifications for incremental sync`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
				"event_queue_arn": schema.StringAttribute{
					MarkdownDescription: `Event Queue ARN

    ARN of the SQS queue receiving S3 event notifications`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
				"external_id": schema.StringAttribute{
					MarkdownDescription: `External ID

    External ID for the IAM role`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
				"iam_role_arn": schema.StringAttribute{
					MarkdownDescription: `IAM Role ARN`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           false,
				},
				"is_directory_snapshot": schema.BoolAttribute{
					MarkdownDescription: `Multi-directory multi-table`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           false,
				},
				"is_single_table": schema.BoolAttribute{
					MarkdownDescription: `Files are time-based snapshots

    Treat the files as a single table.`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
				"s3_bucket_name": schema.StringAttribute{
					MarkdownDescription: `S3 Bucket Name

    Bucket name (folder optional); ex: s3://polytomic/dataset`,
					Required:  true,
					Optional:  false,
					Computed:  false,
					Sensitive: false,
				},
				"s3_bucket_region": schema.StringAttribute{
					MarkdownDescription: `S3 Bucket Region`,
					Required:            true,
					Optional:            false,
					Computed:            false,
					Sensitive:           false,
				},
				"single_table_file_format": schema.StringAttribute{
					MarkdownDescription: `File format`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           false,
				},
				"single_table_file_formats": schema.SetAttribute{
					MarkdownDescription: `File formats

    File formats that may be present across different tables`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,

					ElementType: types.StringType,
				},
				"single_table_name": schema.StringAttribute{
					MarkdownDescription: `Collection name`,
					Required:            false,
					Optional:            true,
					Computed:            true,
					Sensitive:           false,
				},
				"skip_lines": schema.Int64Attribute{
					MarkdownDescription: `Skip first lines

    Skip first N lines of each CSV file.`,
					Required:  false,
					Optional:  true,
					Computed:  true,
					Sensitive: false,
				},
			},

			Required: true,

			PlanModifiers: []planmodifier.Object{
				objectplanmodifier.UseStateForUnknown(),
			},
		},
		"force_destroy": schema.BoolAttribute{
			MarkdownDescription: forceDestroyMessage,
			Optional:            true,
		},
		"id": schema.StringAttribute{
			Computed:            true,
			MarkdownDescription: "S3 Connection identifier",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
	},
}

func (t *S3ConnectionResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = S3Schema
}

type S3Conf struct {
	Auth_mode                  string   `mapstructure:"auth_mode" tfsdk:"auth_mode"`
	Aws_access_key_id          string   `mapstructure:"aws_access_key_id" tfsdk:"aws_access_key_id"`
	Aws_secret_access_key      string   `mapstructure:"aws_secret_access_key" tfsdk:"aws_secret_access_key"`
	Aws_user                   string   `mapstructure:"aws_user" tfsdk:"aws_user"`
	Csv_has_headers            bool     `mapstructure:"csv_has_headers" tfsdk:"csv_has_headers"`
	Directory_glob_pattern     string   `mapstructure:"directory_glob_pattern" tfsdk:"directory_glob_pattern"`
	Enable_event_notifications bool     `mapstructure:"enable_event_notifications" tfsdk:"enable_event_notifications"`
	Event_queue_arn            string   `mapstructure:"event_queue_arn" tfsdk:"event_queue_arn"`
	External_id                string   `mapstructure:"external_id" tfsdk:"external_id"`
	Iam_role_arn               string   `mapstructure:"iam_role_arn" tfsdk:"iam_role_arn"`
	Is_directory_snapshot      bool     `mapstructure:"is_directory_snapshot" tfsdk:"is_directory_snapshot"`
	Is_single_table            bool     `mapstructure:"is_single_table" tfsdk:"is_single_table"`
	S3_bucket_name             string   `mapstructure:"s3_bucket_name" tfsdk:"s3_bucket_name"`
	S3_bucket_region           string   `mapstructure:"s3_bucket_region" tfsdk:"s3_bucket_region"`
	Single_table_file_format   string   `mapstructure:"single_table_file_format" tfsdk:"single_table_file_format"`
	Single_table_file_formats  []string `mapstructure:"single_table_file_formats" tfsdk:"single_table_file_formats"`
	Single_table_name          string   `mapstructure:"single_table_name" tfsdk:"single_table_name"`
	Skip_lines                 int64    `mapstructure:"skip_lines" tfsdk:"skip_lines"`
}

type S3ConnectionResource struct {
	provider *providerclient.Provider
}

func (r *S3ConnectionResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if provider := providerclient.GetProvider(req.ProviderData, resp.Diagnostics); provider != nil {
		r.provider = provider
	}
}

func (r *S3ConnectionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_s3_connection"
}

func (r *S3ConnectionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data connectionData

	diags := req.Config.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connConf, err := objectMapValue(ctx, data.Configuration)
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection configuration", err.Error())
		return
	}
	created, err := client.Connections.Create(ctx, &polytomic.CreateConnectionRequestSchema{
		Name:           data.Name.ValueString(),
		Type:           "s3",
		OrganizationId: data.Organization.ValueStringPointer(),
		Configuration:  connConf,
		Validate:       pointer.ToBool(false),
	})
	if err != nil {
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error creating connection: %s", err))
		return
	}
	data.Id = types.StringPointerValue(created.Data.Id)
	data.Name = types.StringPointerValue(created.Data.Name)
	data.Organization = types.StringPointerValue(created.Data.OrganizationId)

	conf := S3Conf{}
	err = mapstructure.Decode(created.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error decoding connection configuration: %s", err))
	}

	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"auth_mode":                  types.StringType,
		"aws_access_key_id":          types.StringType,
		"aws_secret_access_key":      types.StringType,
		"aws_user":                   types.StringType,
		"csv_has_headers":            types.BoolType,
		"directory_glob_pattern":     types.StringType,
		"enable_event_notifications": types.BoolType,
		"event_queue_arn":            types.StringType,
		"external_id":                types.StringType,
		"iam_role_arn":               types.StringType,
		"is_directory_snapshot":      types.BoolType,
		"is_single_table":            types.BoolType,
		"s3_bucket_name":             types.StringType,
		"s3_bucket_region":           types.StringType,
		"single_table_file_format":   types.StringType,
		"single_table_file_formats": types.SetType{
			ElemType: types.StringType,
		},
		"single_table_name": types.StringType,
		"skip_lines":        types.NumberType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	tflog.Trace(ctx, "created a connection", map[string]interface{}{"type": "S3", "id": created.Data.Id})

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *S3ConnectionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data connectionData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddWarning("Error getting client; trying partner client", err.Error())
		client, err = r.provider.PartnerClient()
	}
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connection, err := client.Connections.Get(ctx, data.Id.ValueString())
	if err != nil {
		pErr := &ptcore.APIError{}
		if errors.As(err, &pErr) {
			if pErr.StatusCode == http.StatusNotFound {
				resp.State.RemoveResource(ctx)
				return
			}
		}
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error reading connection: %s", err))
		return
	}
	data.Id = types.StringPointerValue(connection.Data.Id)
	data.Name = types.StringPointerValue(connection.Data.Name)
	data.Organization = types.StringPointerValue(connection.Data.OrganizationId)

	configAttributes, ok := getConfigAttributes(S3Schema)
	if !ok {
		resp.Diagnostics.AddError("Error getting connection configuration attributes", "Could not get configuration attributes")
		return
	}

	originalConfData, err := objectMapValue(ctx, data.Configuration)
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection configuration", err.Error())
		return
	}

	// reset sensitive values so terraform doesn't think we have changes
	connection.Data.Configuration = resetSensitiveValues(configAttributes, originalConfData, connection.Data.Configuration)

	conf := S3Conf{}
	err = mapstructure.Decode(connection.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error decoding connection configuration: %s", err))
	}

	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"auth_mode":                  types.StringType,
		"aws_access_key_id":          types.StringType,
		"aws_secret_access_key":      types.StringType,
		"aws_user":                   types.StringType,
		"csv_has_headers":            types.BoolType,
		"directory_glob_pattern":     types.StringType,
		"enable_event_notifications": types.BoolType,
		"event_queue_arn":            types.StringType,
		"external_id":                types.StringType,
		"iam_role_arn":               types.StringType,
		"is_directory_snapshot":      types.BoolType,
		"is_single_table":            types.BoolType,
		"s3_bucket_name":             types.StringType,
		"s3_bucket_region":           types.StringType,
		"single_table_file_format":   types.StringType,
		"single_table_file_formats": types.SetType{
			ElemType: types.StringType,
		},
		"single_table_name": types.StringType,
		"skip_lines":        types.NumberType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *S3ConnectionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data connectionData

	diags := req.Plan.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	connConf, err := objectMapValue(ctx, data.Configuration)
	if err != nil {
		resp.Diagnostics.AddError("Error getting connection configuration", err.Error())
		return
	}

	configAttributes, ok := getConfigAttributes(S3Schema)
	if !ok {
		resp.Diagnostics.AddError("Error getting connection configuration attributes", "Could not get configuration attributes")
		return
	}

	var prevData connectionData

	diags = req.State.Get(ctx, &prevData)
	resp.Diagnostics.Append(diags...)

	connConf = handleSensitiveValues(ctx, configAttributes, connConf, prevData.Configuration.Attributes())

	updated, err := client.Connections.Update(ctx,
		data.Id.ValueString(),
		&polytomic.UpdateConnectionRequestSchema{
			Name:           data.Name.ValueString(),
			OrganizationId: data.Organization.ValueStringPointer(),
			Configuration:  connConf,
			Validate:       pointer.ToBool(false),
		})
	if err != nil {
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error updating connection: %s", err))
		return
	}

	data.Id = types.StringPointerValue(updated.Data.Id)
	data.Name = types.StringPointerValue(updated.Data.Name)
	data.Organization = types.StringPointerValue(updated.Data.OrganizationId)

	conf := S3Conf{}
	err = mapstructure.Decode(updated.Data.Configuration, &conf)
	if err != nil {
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error decoding connection configuration: %s", err))
	}

	data.Configuration, diags = types.ObjectValueFrom(ctx, map[string]attr.Type{
		"auth_mode":                  types.StringType,
		"aws_access_key_id":          types.StringType,
		"aws_secret_access_key":      types.StringType,
		"aws_user":                   types.StringType,
		"csv_has_headers":            types.BoolType,
		"directory_glob_pattern":     types.StringType,
		"enable_event_notifications": types.BoolType,
		"event_queue_arn":            types.StringType,
		"external_id":                types.StringType,
		"iam_role_arn":               types.StringType,
		"is_directory_snapshot":      types.BoolType,
		"is_single_table":            types.BoolType,
		"s3_bucket_name":             types.StringType,
		"s3_bucket_region":           types.StringType,
		"single_table_file_format":   types.StringType,
		"single_table_file_formats": types.SetType{
			ElemType: types.StringType,
		},
		"single_table_name": types.StringType,
		"skip_lines":        types.NumberType,
	}, conf)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r *S3ConnectionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data connectionData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	client, err := r.provider.Client(data.Organization.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error getting client", err.Error())
		return
	}
	if data.ForceDestroy.ValueBool() {
		err := client.Connections.Remove(ctx, data.Id.ValueString(), &polytomic.ConnectionsRemoveRequest{
			Force: pointer.ToBool(true),
		})
		if err != nil {
			pErr := &polytomic.NotFoundError{}
			if errors.As(err, &pErr) {
				resp.State.RemoveResource(ctx)
				return
			}

			resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error deleting connection: %s", err))
		}
		return
	}

	err = client.Connections.Remove(ctx, data.Id.ValueString(), &polytomic.ConnectionsRemoveRequest{
		Force: pointer.ToBool(false),
	})
	if err != nil {
		pErr := &polytomic.NotFoundError{}
		if errors.As(err, &pErr) {
			resp.State.RemoveResource(ctx)
			return
		}
	}
	pErr := &polytomic.UnprocessableEntityError{}
	if errors.As(err, &pErr) {
		if strings.Contains(*pErr.Body.Message, "connection in use") {
			if used_by, ok := pErr.Body.Metadata["used_by"].([]interface{}); ok {
				for _, us := range used_by {
					if user, ok := us.(map[string]interface{}); ok {
						resp.Diagnostics.AddError("Connection in use",
							fmt.Sprintf("Connection is used by %s \"%s\" (%s). Please remove before deleting this connection.",
								user["type"], user["name"], user["id"]),
						)
					}
				}
				return
			}
		}
	}

	if err != nil {
		resp.Diagnostics.AddError(providerclient.ErrorSummary, fmt.Sprintf("Error deleting connection: %s", err))
	}
}

func (r *S3ConnectionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
